---
title: "Ecology Assignment 2"
author: "Sandra Fogg"
date: "3/5/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#Load Packages in Console

#Load Data Sets
fertilizer_df <- read_csv("fertilizer.csv")
grain_df <- read_csv("grain.csv")
```
##1. Patterns in Yield Over Time

####Create a Finalized Graph of Yield Over Time for Each Grain
```{r}
#Create All Crops Dataframe
all_crops_clean <- grain_df %>%
  filter(yield != "NA")
#Create All Crops Plot
all_crops_plot_yield <- ggplot(all_crops_clean, aes(x=year, y=yield)) +
  geom_line(aes(color = commodity)) +
  labs(y = "Crop Yield (bushels/acre)", x = "Year", color = "Commodity") +
  theme_classic() +
  ggtitle("US Agricultural Crop Yield from 1866 to 2016") +
  scale_y_continuous(expand = c(0,0), limits = c(0, 180), breaks = seq(0, 180, 20)) +
  scale_x_continuous(expand= c(0,0), breaks = seq(1866, 2016, 20))
  
all_crops_plot_yield


#SAME PLOT BUT FACET WRAPPED FOR SEPARATENESS
all_crops_plot_FACET <- ggplot(all_crops_clean, aes(x=year, y=yield)) +
  geom_line() +
  labs(y = "Crop Yield (bushels/acre)", x = "Year", color = "Commodity") +
  theme_classic() +
  ggtitle("US Agricultural Crop Yield from 1866 to 2016") +
  scale_y_continuous(expand = c(0,0), limits = c(0, 180), breaks = seq(0, 180, 30)) +
  scale_x_continuous(expand= c(0,0), breaks = seq(1866, 2016, 30))+
  facet_wrap(~commodity, scale = "free")
  
all_crops_plot_FACET



```

##2. Fertilizer Use

####Create a Finalized Plot of Fertilizer Use vs. Time for Each Crop
```{r}
#Create Wheat Dataframe
fertilizer_wheat <- fertilizer_df %>%
  filter(ppa != "NA",
         crop == "Wheat")
#Create Wheat Plot
wheat_plot <- ggplot(fertilizer_wheat, aes(x=year, y=ppa)) +
  geom_line(aes(color = fertilizer)) +
  labs(y = "Fertilizer Application (lbs/acre)", x = "Year", color = "Fertilizer") +
  theme_classic() +
  ggtitle("US Agricultural Fertilizer Use on Wheat from 1964 to 2016") +
  scale_y_continuous(expand = c(0,0), limits = c(0, 100), breaks = seq(0, 100, 10)) +
  scale_x_continuous(expand= c(0,0), breaks = seq(1964, 2024, 10))+
  scale_color_brewer(palette = "Dark2")
  
wheat_plot


#Create Corn Dataframe
fertilizer_corn <- fertilizer_df %>%
  filter(ppa != "NA",
         crop == "Corn")
#Create Corn Plot
wheat_plot <- ggplot(fertilizer_corn, aes(x=year, y=ppa)) +
  geom_line(aes(color = fertilizer)) +
  labs(y = "Fertilizer Application (lbs/acre)", x = "Year", color = "Fertilizer") +
  theme_classic() +
  ggtitle("US Agricultural Fertilizer Use on Corn from 1964 to 2016") +
  scale_y_continuous(expand = c(0,0), limits = c(0, 100), breaks = seq(0, 100, 10)) +
  scale_x_continuous(expand= c(0,0), breaks = seq(1964, 2024, 10))+
  scale_color_brewer(palette = "Dark2")
  
Corn_plot


#Create Soybean Dataframe
fertilizer_soybean <- fertilizer_df %>%
  filter(ppa != "NA",
         crop == "Soybeans")
#Create Soybean Plot
soybean_plot <- ggplot(fertilizer_soybean, aes(x=year, y=ppa)) +
  geom_line(aes(color = fertilizer)) +
  labs(y = "Fertilizer Application (lbs/acre)", x = "Year", color = "Fertilizer") +
  theme_classic() +
  ggtitle("US Agricultural Fertilizer Use on Soybeans from 1964 to 2016") +
  scale_y_continuous(expand = c(0,0), limits = c(0, 100), breaks = seq(0, 100, 10)) +
  scale_x_continuous(expand= c(0,0), breaks = seq(1964, 2024, 10))+
  scale_color_brewer(palette = "Dark2")
  
soybean_plot


#Create All Crops Plot
all_crops_plot <- ggplot(fertilizer_df, aes(x=year, y=ppa)) +
  geom_line(aes(color = fertilizer)) +
  labs(y = "Fertilizer Application (lbs/acre)", x = "Year", color = "Fertilizer") +
  theme_classic() +
  ggtitle("US Agricultural Fertilizer Use from 1964 to 2016") +
  scale_y_continuous(expand = c(0,0), limits = c(0, 150), breaks = seq(0, 150, 10)) +
  scale_x_continuous(expand= c(0,0), limits = c(1964, 2018), breaks = seq(1964, 2018, 10))+
  scale_color_brewer(palette = "Dark2") +
  facet_wrap(~crop, scale = "free") 
  
all_crops_plot
```
####Describe Differences in Fertilizer Use for Each Crop
```{r}
#Find Differences for Wheat
mwu_wheat <- fertilizer_wheat %>%
  wilcox.test(ppa ~ fertilizer, data = .)
mwu_wheat

#Find Differences for Corn
mwu_corn <- fertilizer_corn %>%
  wilcox.test(ppa ~ fertilizer, data = .)
mwu_corn

#Find Differences for Soybeans
mwu_soybean <- fertilizer_soybean %>%
  wilcox.test(ppa ~ fertilizer, data = .)
mwu_soybean
```



##3. Case Study: Corn and Fertilizer

####Create a Finalized Plot of Corn Yield vs. PPA
```{r}
#Create Corn Yield Dataframe
grain_years_df <- grain_df[grain_df$year >= 1963 & grain_df$year <=2017,] 
corn_yield <- grain_years_df %>% 
  filter(yield != "NA",
         commodity == "Corn")

corn_yield_use <- merge(fertilizer_corn,corn_yield, sort = TRUE)
corn_yield_use
#Create Corn Yield Plot
corn_yield_fert_plot <- ggplot(corn_yield_use, aes(x = ppa, y = yield)) +
  geom_point(aes(color = year, shape = fertilizer), size = 3, alpha = 0.9) +
  labs(y = "Crop Yield (bushels/acre)", x = "Fertilizer Application (lbs/acre)", color = "Year", shape = "Fertilizer") +
  theme_classic() +
  scale_color_gradient(low = "firebrick2", high = "chartreuse") +
  ggtitle("US Fertilizer Use on Corn and Resulting Crop Yield from 1964 to 2016") +
  scale_y_continuous(expand = c(0,0), limits = c(30, 180), breaks = seq(0, 180, 20)) +
  scale_x_continuous(expand= c(0,0), limits = c(30, 160), breaks = seq(0, 160, 20))

  
corn_yield_fert_plot
 
```

